all:lesson1to10 lesson11to20 lesson21to30 lesson31to36
lesson1to10:
	cd lesson01;$(MAKE)
	cd lesson02;$(MAKE)
	cd lesson03;$(MAKE)
	cd lesson04;$(MAKE)
	cd lesson05;$(MAKE)
	cd lesson06;$(MAKE)
	cd lesson07;$(MAKE)
	cd lesson08;$(MAKE)
	cd lesson09;$(MAKE)
	cd lesson10;$(MAKE)
lesson11to20:
	cd lesson11;$(MAKE)
	cd lesson12;$(MAKE)
	cd lesson13;$(MAKE)
	cd lesson14;$(MAKE)
	cd lesson15;$(MAKE)
	cd lesson16;$(MAKE)
	cd lesson17;$(MAKE)
	cd lesson18;$(MAKE)
	cd lesson19;$(MAKE)
	cd lesson20;$(MAKE)
lesson21to30:
	cd lesson21;$(MAKE)
	cd lesson22;$(MAKE)
	cd lesson23;$(MAKE)
	cd lesson24;$(MAKE)
	cd lesson25;$(MAKE)
	cd lesson26;$(MAKE)
	cd lesson27;$(MAKE)
	cd lesson28;$(MAKE)
	cd lesson29;$(MAKE)
	cd lesson30;$(MAKE)			
lesson31to36:
	cd lesson31;$(MAKE)
	cd lesson32;$(MAKE)
	cd lesson33;$(MAKE)
	cd lesson34;$(MAKE)
	cd lesson35;$(MAKE)
	cd lesson36;$(MAKE)

clean:
	cd lesson01;$(MAKE) clean 
	cd lesson02;$(MAKE) clean
	cd lesson03;$(MAKE) clean	
	cd lesson04;$(MAKE) clean 
	cd lesson05;$(MAKE) clean
	cd lesson06;$(MAKE) clean
	cd lesson07;$(MAKE) clean 
	cd lesson08;$(MAKE) clean 
	cd lesson09;$(MAKE) clean 
	cd lesson10;$(MAKE) clean 
	cd lesson11;$(MAKE) clean 
	cd lesson12;$(MAKE) clean 
	cd lesson13;$(MAKE) clean 
	cd lesson14;$(MAKE) clean 
	cd lesson15;$(MAKE) clean 
	cd lesson16;$(MAKE) clean 
	cd lesson17;$(MAKE) clean
	cd lesson18;$(MAKE) clean
	cd lesson19;$(MAKE) clean
	cd lesson20;$(MAKE) clean
	cd lesson21;$(MAKE) clean
	cd lesson22;$(MAKE) clean
	cd lesson23;$(MAKE) clean
	cd lesson24;$(MAKE) clean
	cd lesson25;$(MAKE) clean
	cd lesson26;$(MAKE) clean
	cd lesson27;$(MAKE) clean
	cd lesson28;$(MAKE) clean
	cd lesson29;$(MAKE) clean
	cd lesson30;$(MAKE) clean
	cd lesson31;$(MAKE) clean
	cd lesson32;$(MAKE) clean
	cd lesson33;$(MAKE) clean
	cd lesson34;$(MAKE) clean
	cd lesson35;$(MAKE) clean
	cd lesson36;$(MAKE) clean
